### PR TITLE
Fix video corruption for non-multiple-of-8 gop size 

### LINKED ISSUE #70: ffmpeg: Video corrupted
Building on SVT-VP9 master (615e4a4) with FFmpeg master (4d980a8ceb) on Ubuntu 19.10

``` bash
git clone https://github.com/OpenVisualCloud/SVT-VP9.git
cd SVT-VP9/Build/linux
cmake ../.. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
make -j $(nproc) && sudo make install
cd -
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
curl https://raw.githubusercontent.com/OpenVisualCloud/SVT-VP9/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch | git am
mkdir build && cd build
../configure --enable-libsvtvp9 --enable-static --disable-shared && make -j $(nproc)
youtube-dl -f 137 i1IKnWDecwA -o phoenix.mp4 # 1080p24 fps video only, no audio selected
./ffmpeg -i phoenix.mp4 -c:v libsvt_vp9 phoenix.ivf
```

Original video ~2 seconds in. Played through vlc (Latest 3.0.8 Windows 10)
vlcsnap-2019-11-07-14h59m40s094

Encoded video ~2 seconds in. Played through vlc (Latest 3.0.8 Windows 10)
vlcsnap-2019-11-07-14h54m28s388

### PR DESCRIPTION
**Pull request by intelmark**
Fixes #70

### CODE REVIEW

File: Source/Lib/Codec/EbPictureDecisionProcess.c [hunk 1]
```diff
@@ -1641,27 +1642,26 @@ void* picture_decision_kernel(void *input_ptr)
...
-                picture_control_set_ptr->idr_flag =
-                    (sequence_control_set_ptr->intra_refresh_type != IDR_REFRESH) ?
-                        picture_control_set_ptr->idr_flag :
-                        (encode_context_ptr->intra_period_position == (uint32_t) sequence_control_set_ptr->intra_period) ?
-                            EB_TRUE :
-                            picture_control_set_ptr->idr_flag;
-
-            }
+           picture_control_set_ptr->cra_flag = EB_FALSE;
+           picture_control_set_ptr->idr_flag = EB_FALSE;
```
Comment (tianjunwork) [inline Source/Lib/Codec/EbPictureDecisionProcess.c]: For HEVC, we have a recent fix removing below two lines.
           picture_control_set_ptr->cra_flag = EB_FALSE;
           picture_control_set_ptr->idr_flag = EB_FALSE;
Could you check code on current tip of HEVC?

File: Source/App/EbAppConfig.c [hunk 2]
```diff
@@ -311,7 +311,7 @@ void eb_config_ctor(EbConfig *config_ptr)
 
     config_ptr->enc_mode                                         = 9;
     config_ptr->intra_period                                     = -2;
-    config_ptr->intra_refresh_type                               = 1;
+    config_ptr->intra_refresh_type                               = 2;
```
Comment (tianjunwork) [inline Source/App/EbAppConfig.c]: why is the change here? should we also update default value in user guide?

**Comment by 1480c1** [comment]
Does this address a certain issue? Is this related to #70?

**Comment by tianjunwork** [comment]
closes #70

**Comment by 1480c1** [comment]
image
Slightly better, however, I can't get the exact same frame as the one in #70 since it seems to skip that one. Feels like it's visually lagging and limping

**Comment by tianjunwork** [comment]
You mean one input frame is skipped? You can double check with a video with running timestamp overlay. We will check it too on Monday.

File: Source/Lib/Codec/EbPictureDecisionProcess.c (hunk 1 above)
Comment (intelmark) [reply Source/Lib/Codec/EbPictureDecisionProcess.c]: The current tip of HEVC does have these removed and it will be OK to remove these in this PR.

File: Source/App/EbAppConfig.c (hunk 2 above)
Comment (intelmark) [reply Source/App/EbAppConfig.c]: The default value for intra refresh seems a bit inconsistent among the encoders.  
In AV1 the default is CRA.
In HEVC the user guide and cfg file show that CRA is the default, however in EbAppConfg the default is set to IDR

Seems like the problem in VP9 is resolved when the intra refresh is set to IDR, but not sure if there's another problem (perhaps with references) that fix would be masking.

Comment (Austin-Hu) [reply Source/App/EbAppConfig.c]: Hi @intelmark , please refer to the new change for the default value in HEVC PR #[435](https://github.com/OpenVisualCloud/SVT-HEVC/pull/435). Thanks!

**Comment by tianjunwork** [comment]
Hi @intelmark could you also verify what Chris reported in https://github.com/OpenVisualCloud/SVT-VP9/pull/72#issuecomment-559988782? Could you reproduce?

**Comment by intelmark** [comment]
Hi @1480c1 - We verified that the VP9 encoder with this PR applied doesn't seem to drop any frames (using a timestamped file).  Can you re-verify with the latest changes, and provide us with a sample file that demonstrates the lag problem and/or identify the skipped frame?

thanks!

**Comment by 1480c1** [comment]
```bash
git checkout master
git pull upstream master
git fetch upstream pull/72/head
git merge --no-commit --no-ff --no-gpg-sign FETCH_HEAD
mkdir build-72
cd build-72
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF
cd ../Bin/Debug
./SvtVp9EncApp -i ~/phoenix.yuv -w 1920 -h 1080 -fps 24 -b phoenix.ivf
```

```
Encoding         7SVT [ERROR]: disp_order_continuity_count Error1 POC:32
        8
```

File: Config/Sample.cfg [hunk 3]
```diff
@@ -44,7 +44,7 @@ BaseLayerSwitchMode             : 0             # 0 : Use B-frames in the base l
 PredStructure                   : 2             # 2: Random Access
 
 IntraPeriod                     : 47            # Period of I-Frame (-1 = only first, -2 = auto) [-2 - 255]
-IntraRefreshType                : 2             # Random Accesss 1:CRA, 2:IDR (when intra_period > 0) - [1-2]
+IntraRefreshType                : 1             # Random Access 1:CRA, 2:IDR (when intra_period > 0) - [1-2]
```
Comment (tianjunwork) [inline Config/Sample.cfg]: should it be 2 IDR? pls also update user guide?

**Comment by tianjunwork** [comment]
Please fix the build error.

File: Config/Sample.cfg (hunk 3 above)
Comment (intelmark) [reply Config/Sample.cfg]: yes, updated in user guide and config file to match (default is 2=IDR)

File: Source/Lib/Codec/EbPictureDecisionProcess.c (hunk 1 above)
Comment (tianjunwork) [reply Source/Lib/Codec/EbPictureDecisionProcess.c]: Hi Mark, these two lines are still here? Could you remove them?

**Comment by tianjunwork** [comment]
Review comment is still pending in Source/Lib/Codec/EbPictureDecisionProcess.c.

**Comment by 1480c1** [comment]
@intelmark ping?

**Comment by intelmark** [comment]
@1480c1 - sorry for the delay.  We had some discussions about the best way to resolve this as a similar AV1 solution we were hoping to apply to this issue didn't quite map well to VP9.   I expect to revise the PR this week.

**Comment by tianjunwork** [comment]
Hi @1480c1, could you remind me again that what is the similar fix for appveyor here from svt-av1? Thank you:)

**Comment by 1480c1** [comment]
> Hi @1480c1, could you remind me again that what is the similar fix for appveyor here from svt-av1? Thank you:)

https://github.com/OpenVisualCloud/SVT-AV1/commit/ebd9c80d414c323d8cccdc362f4399b6a9979dda#diff-280dcd3e39e9dfff92d2c1dc5e3a6387
Here's the commit

We can just disable ffmpeg building for appveyor except mingw-w64+release if wanted since it takes some time

**Comment by tianjunwork** [comment]
Hi @intelmark, could you do a quick double check if IDR request still works? By changing
`header_ptr->pic_type     = EB_INVALID_PICTURE;` to `EB_IDR_PICTURE` in EbAppProcessCmd.c? Thank you.

**Comment by tianjunwork** [comment]
Thank you @1480c1. The assertion will be addressed in another PR.

**Comment by intelmark** [comment]
@tianjunwork - Changing
header_ptr->pic_type = EB_INVALID_PICTURE; to EB_IDR_PICTURE in EbAppProcessCmd.c
results in every frame being a keyframe
